spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/store
    username: root
    password: yz2000813
mybatis:
  configuration:
    map-underscore-to-camel-case: true
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 15MB

